# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'


steps:
- task: Docker@2
  displayName: Login to RedHat Repo
  inputs:
    containerRegistry: 'RedHat Catalog Registry'
    command: 'login'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo ''{  "insecure-registries" : ["default-route-openshift-image-registry.apps.cluster-7c40.sandbox601.opentlc.com"]}'' > $(DOCKER_CONFIG)/daemon.json'
- task: Docker@2
  inputs:
    containerRegistry: 'Internal OCP Repo'
    command: 'login'

- task: Docker@2
  inputs:
    containerRegistry: 'Internal OCP Repo'
    repository: 'demoblog/demoblog'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: latest

