# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'


steps:
- task: Docker@2
  displayName: Login to RedHat Repo
  inputs:
    containerRegistry: 'RedHat Catalog Registry'
    command: 'login'

- task: Docker@2
  displayName: Login to internal OpenShift Repo
  inputs:
      containerRegistry: 
      command: login
  
- task: Docker@2
  displayName: Build an image
  inputs:
    command: 'buildAndPush'
    containerRegistry: 
    Dockerfile: '**/Dockerfile'
    repository: 
    tags: latest
